services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./smartspend-backend
    container_name: smartspend-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/smartspend

  frontend:
    build: ./smartspend
    container_name: smartspend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data: